[package]
authors = ["Daniel Garcia <danigm@wadobo.com>"]
name = "fractal-matrix-api"
version = "4.0.0"
workspace = "../"
edition = "2018"

description = """
Library to communicate with a Matrix.org server
"""
keywords = [
    "matrix", "fractal"
]
license = "GPL-3.0"
repository = "https://gitlab.gnome.org/GNOME/fractal"
documentation = "https://gnome.pages.gitlab.gnome.org/fractal/fractal_matrix_api/index.html"

[dependencies]
glib = "0.6.1"
lazy_static = "1.2.0"
log = "0.4.6"
md5 = "0.6.1"
regex = "1.1.0"
reqwest = "0.9.5"
serde_json = "1.0.33"
time = "0.1.41"
tree_magic = "0.2.1"
url = "1.7.2"
urlencoding = "1.0.0"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]

[dependencies.serde]
version = "1.0.82"
features = ["derive"]
