[package]
authors = ["Daniel Garcia <danigm@wadobo.com>"]
name = "fractal-matrix-api"
version = "3.30.0"
workspace = "../"

description = """
Library to communicate with a Matrix.org server
"""
keywords = [
    "matrix", "fractal"
]
license = "GPL-3.0"
repository = "https://gitlab.gnome.org/World/fractal"
documentation = "https://world.pages.gitlab.gnome.org/fractal/fractal_matrix_api/index.html"

[dependencies]
log = "0.4.5"
glib = "0.6.0"
regex = "1.0.5"
reqwest = "0.9.4"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
time = "0.1.40"
tree_magic = "0.2.0"
url = "1.7.1"
urlencoding = "1.0.0"
md5 = "0.5.0"

[dependencies.cairo-rs]
features = ["png"]
version = "0.5.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.6"
